= REST HTTP Java Application implementing Quarkus and JPAStreamer 

== Prerequisites
- Java 11 or later
- Docker
- Sakila database running in a Docker container, see instructions xref:database[here].

[#database]
== Database
The application makes use of the link:https://dev.mysql.com/doc/sakila/en/[MySQL Sakila sample database]. To download and run it as a Docker container on port 3306, run:

[shell script]
----
$ docker run -d --publish 3306:3306 --name mysqld restsql/mysql-sakila
----

== Running the application in dev mode
You can run your application in dev mode that enables live coding using:

[source, shell]
----
./mvnw compile quarkus:dev
----

NOTE: The Quarkus Dev UI is available in dev mode only at link:http://localhost:8080/q/dev/[http://localhost:8080/q/dev/].

NOTE: To test your endpoints using Swagger, visit link:http://localhost:8080/q/swagger-ui/[http://localhost:8080/q/swagger-ui/].

== Packaging and running the application
The application can be packaged using:

[source, shell]
----
./mvnw package
----

It produces the `quarkus-run.jar` file in the `target/quarkus-app/` directory.
The application is now runnable using `java -jar target/quarkus-app/quarkus-run.jar`.
